import { provideIcons } from '@ng-icons/core';
import {
  lucideActivity,
  lucideBedDouble,
  lucideBriefcase,
  lucideBuilding2,
  lucideCalendarCheck,
  lucideCalendarDays,
  lucideChartBar,
  lucideDoorOpen,
  lucideInbox,
  lucideLayoutDashboard,
  lucideLogIn,
  lucideLogOut,
  lucideMenu,
  lucideMoreVertical,
  lucidePanelLeftClose,
  lucidePanelLeftOpen,
  lucidePlus,
  lucideScrollText,
  lucideTag,
  lucideUndo2,
  lucideUserCog,
  lucideUserPlus,
  lucideUsers,
  lucideWallet,
} from '@ng-icons/lucide';

export const appIconProviders = provideIcons({
  lucideActivity,
  lucideBedDouble,
  lucideBriefcase,
  lucideBuilding2,
  lucideCalendarCheck,
  lucideCalendarDays,
  lucideChartBar,
  lucideDoorOpen,
  lucideInbox,
  lucideLayoutDashboard,
  lucideLogIn,
  lucideLogOut,
  lucideMenu,
  lucideMoreVertical,
  lucidePanelLeftClose,
  lucidePanelLeftOpen,
  lucidePlus,
  lucideScrollText,
  lucideTag,
  lucideUndo2,
  lucideUserCog,
  lucideUserPlus,
  lucideUsers,
  lucideWallet,
});
